[build.environment]
  NPM_FLAGS = "--version"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
[build]
#    publish = ".dist"
    command = "npm i react-copy-to-clipboard && npm install pnpm && pnpm run build"
